version: 2
jobs:
  build:
    working_directory: ~/atm
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: apt-get -qq update
      - run: apt-get -qq -y install libmysqlclient-dev
      - run: tox
